analytics: {}
color:
  brandColors:
    - '#D8D8D0'
    - '#701800'
    - '#507090'
    - '#D03800'
    - '#000000'
  brandStrength: 0.017736
  lightness: 0.875102
  rhythmicContrast: 0.201285
  saturation: 0.513513
cta: {}
layout_spectrum: 0.009291
name: www.servoglitch.com
opengraph: {}
purpose: {}
typography_spectrum: 0
